/* Generated By:JJTree: Do not edit this line. ASTappl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTappl extends SimpleNode {
  public ASTappl(int id) {
    super(id);
  }

  public ASTappl(Prog3 p, int id) {
    super(p, id);
  }
	
	 public ASTappl clone(int id){
    return new ASTappl(id);
  }
  
}
/* JavaCC - OriginalChecksum=7a5eeda7683909e16c9c1affa7a0d07a (do not edit this line) */
