/* Generated By:JJTree: Do not edit this line. ASTadd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTadd extends SimpleNode {
  public ASTadd(int id) {
    super(id);
  }

  public ASTadd(Prog3 p, int id) {
    super(p, id);
  }
  
  public ASTadd clone(int id){
    return new ASTadd(id);
  }

}
/* JavaCC - OriginalChecksum=65ac38431cee0f014ed357f7687acc16 (do not edit this line) */
