/* Generated By:JJTree: Do not edit this line. ASTdiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdiv extends SimpleNode {
  public ASTdiv(int id) {
    super(id);
  }

  public ASTdiv(Prog3 p, int id) {
    super(p, id);
  }
public ASTdiv clone(int id){
    return new ASTdiv(id);
  }
}
/* JavaCC - OriginalChecksum=1f9059af5c0e7764bde26091cbe72b28 (do not edit this line) */
