/* Generated By:JJTree: Do not edit this line. ASTmult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmult extends SimpleNode {
  public ASTmult(int id) {
    super(id);
  }

  public ASTmult(Prog3 p, int id) {
    super(p, id);
  }
public ASTmult clone(int id){
    return new ASTmult(id);
  }
}
/* JavaCC - OriginalChecksum=954e2f5b055c8b480a76aedd7a9fdbe0 (do not edit this line) */
