/* Generated By:JJTree: Do not edit this line. ASTsub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsub extends SimpleNode {
  public ASTsub(int id) {
    super(id);
  }

  public ASTsub(Prog3 p, int id) {
    super(p, id);
  }
	public ASTsub clone(int id){
		return new ASTsub(id);
  }
}
/* JavaCC - OriginalChecksum=b292c2da988e14573689e4a6508d18e8 (do not edit this line) */
