/* Generated By:JavaCC: Do not edit this line. Prog3TreeConstants.java Version 5.0 */
public interface Prog3TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTMULT = 4;
  public int JJTDIV = 5;
  public int JJTLAMB = 6;
  public int JJTAPPL = 7;
  public int JJTMYID = 8;
  public int JJTINTEGER = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "add",
    "sub",
    "mult",
    "div",
    "lamb",
    "appl",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=b671cf26109d740369a762c4c53405d5 (do not edit this line) */
